# Generated by Django 5.1.5 on 2025-01-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_amenities"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=180),
        ),
        migrations.AlterField(
            model_name="room",
            name="city",
            field=models.CharField(default="Cupertino", max_length=80),
        ),
    ]
