# Generated by Django 5.1.4 on 2025-01-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='price',
        ),
        migrations.AddField(
            model_name='house',
            name='price_per_night',
            field=models.PositiveIntegerField(db_column='price', default=0, help_text='Please enter the price per night in USD', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='house',
            name='pets_allowed',
            field=models.BooleanField(default=True, help_text='Does this house allow pets?', verbose_name='Pets allowed'),
        ),
    ]
